language: elixir
elixir: '1.7.0'
otp_release: '21.0'
sudo: required
notifications:
  email: false
env:
  global:
    - MIX_ENV=test
    - PORT=7070
script:
  - mix format --check-formatted
  - mix test
